knp_snappy:
    pdf:
        enabled:    true
        binary:     '"C:\Program Files (x86)\wkhtmltopdf\bin\wkhtmltopdf.exe"'
        options:    []
    image:
        enabled:    true
        binary:     '%env(WKHTMLTOIMAGE_PATH)%'
        options:    []
