knpu_oauth2_client:
    clients:
        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
        google: 
            type: google
            client_id: '%env(GOOGLE_OAUTH_ID)%'
            client_secret: '%env(GOOGLE_OAUTH_SECRET)%'
            redirect_route: auth_oauth_check
            redirect_params: 
                service: google