controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
api_search_address:
    path: /api/search_address
    controller: App\Controller\AddressApiController::search
