<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNNFXrUn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNNFXrUn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNNFXrUn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNNFXrUn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNNFXrUn\App_KernelDevDebugContainer([
    'container.build_hash' => 'NNFXrUn',
    'container.build_id' => '0ac97ffe',
    'container.build_time' => 1709125553,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNNFXrUn');
