<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYxIZgOt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYxIZgOt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYxIZgOt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYxIZgOt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYxIZgOt\App_KernelDevDebugContainer([
    'container.build_hash' => 'YxIZgOt',
    'container.build_id' => '0f165e60',
    'container.build_time' => 1709218007,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYxIZgOt');
