<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNsqIqIb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNsqIqIb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNsqIqIb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNsqIqIb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNsqIqIb\App_KernelDevDebugContainer([
    'container.build_hash' => 'NsqIqIb',
    'container.build_id' => 'd9c6f0a8',
    'container.build_time' => 1709113748,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNsqIqIb');
